### PR TITLE
Fix: Update Vendor-Specific OCF values

### PR DESCRIPTION
**Pull request by AbbyWolf-ADI**

### CODE REVIEW

**Comment by kevin-gillespie** [comment]
The OCF changes look good. I think we need to merge main into here to resolve the conflicts.

**Comment by EricB-ADI** [comment]
> The OCF changes look good. I think we need to merge main into here to resolve the conflicts.
> 
> Do we need to make these changes in the Packetcraft-ADI repo?

These changes were to match the PC-ADI repo.

**Comment by EricB-ADI** [comment]
The linter is being weird. I am running pylint locally which uses 3.10 and there is not issue.

```bash
❯ pylint --version
pylint 2.17.4
astroid 2.15.5
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0]
```

**Comment by EricB-ADI** [comment]
I am, however, more worried about the integration test. It runs the HCI to verify the commands so that needs to pass. If that branch is merged on MSDK it should pass. It doesn't look like the integration part itself is failing though

**Review by EricB-ADI — APPROVED** [review]

**Pull request merged**
